# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6aacb18bf314bd78de8d3b8434c491e4"
name = "Voiceflow in Store"
handle = "voiceflow-in-store"
application_url = "https://single-ext-dont-orientation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0e88c529.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://single-ext-dont-orientation.trycloudflare.com/auth/callback",
  "https://single-ext-dont-orientation.trycloudflare.com/auth/shopify/callback",
  "https://single-ext-dont-orientation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://multiple-projects-holland-logged.trycloudflare.com/webhooks"

[pos]
embedded = false
